version: '3'
services:
    nodejs-server:
        build: ./descendence
        ports:
            - "4200:4200"
        container_name: node-api
        depends_on:
            - nestjs
        volumes:
            - ./descendence:/usr/src/app
    database:
        image: "postgres"
        ports:
            - "5432:5432"
        env_file:
            - ./postgres/database.env
        volumes:
            - database-data:/var/lib/postgresql/data/
        container_name: database
    nestjs:
        depends_on:
            - database
        container_name: nestjs
        image: nestjs:1.0.0
        build: ./nestjs
        ports:
            - 3000:3000
        volumes:
            - ./nestjs:/usr/src/app
            - /usr/src/app/node_modules
#probably needs fixing, data is gone when the container exits
volumes:
    database-data: